# Generated by Django 3.2.8 on 2022-02-11 00:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercollection',
            name='generation_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='FailedUserCollection_Tracker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('collection_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=300)),
                ('dimension_x', models.IntegerField()),
                ('dimension_y', models.IntegerField()),
                ('collection_size', models.IntegerField()),
                ('error_message', models.CharField(blank=True, max_length=500, null=True)),
                ('collection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.usercollection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
